language: node_js
install:
    - npm install
    - ./node_modules/.bin/bower install
script:
    - ./node_modules/.bin/gulp
deploy:
    provider: pages
    github_token: $GITHUB_TOKEN
    skip_cleanup: true
    local_dir: dist
    on:
        branch: master

